quarkus:
  application:
    name: 3scale-cms

  banner:
    enabled: false

  container-image:
    labels:
      # TODO: Get jib to strip these labels
      'com.redhat.build-host': null
      'com.redhat.component': null
      'com.redhat.license_terms': null
      'io.buildah.version': null
      'io.cekit.version': null
      'org.jboss.product': null
      'org.jboss.product.openjdk.version': null
      'org.jboss.product.version': null

      vendor: FwMotion.com
      maintainer: 'Robert Grimm <rgrimm@redhat.com>'
      name: fwmotion/${quarkus.application.name}
      summary: >-
        Image for running jobs to interact with the 3scale Developer Portal CMS
      description: ${quarkus.container-image.labels.summary}
      url: 'https://github.com/fwmotion/3scale-cms'

      'io.k8s.display-name': 3scale CMS CLI Tool
      'io.k8s.description': ${quarkus.container-image.labels.summary}
      'org.opencontainers.image.description': ${quarkus.container-image.labels.description}

  jib:
    environment-variables:
      # Default to path /cms when in a container (otherwise defaults to .)
      THREESCALE_CMS_ROOT: /cms

  log:
    console:
      format: '%s%e%n'
    category:
      'io.quarkus':
        level: ERROR
      'com.fwmotion.threscale.cms.cli':
        level: TRACE
    min-level: TRACE

  native:
    additional-build-args:
      - --report-unsupported-elements-at-runtime

      - --initialize-at-run-time=org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory
      - --initialize-at-run-time=org.apache.hc.client5.http.impl.auth.NTLMEngineImpl
      - --initialize-at-run-time=com.redhat.threescale.rest.cms.Configuration

    enable-http-url-handler: true
    enable-https-url-handler: true

    compression:
      level: 7
      additional-args:
        - --no-lzma
