name: Generate Site and Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      git-ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      git-ref:
        required: true
        type: string

jobs:
  render-site:
    name: Render Site
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout 3scale CMS
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.git-ref }}

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: temurin
        cache: maven
        settings-path: ${{ github.workspace }}
        server-id: github

    - name: Set Up Pages
      uses: actions/configure-pages@v2

    - name: Run Maven Site
      # compile needs to run so Maven figures out cross-module dependencies
      # and stagingDirectory will have a value appended relative to parent for each module
      run: >-
        ./mvnw
        --settings ${{ github.workspace }}/settings.xml
        --batch-mode
        compile
        post-site
        site:stage
        -DstagingDirectory=${{ github.workspace }}/target/staging/parent

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ github.workspace }}/target/staging/.

  deploy-site:
    name: Deploy Site to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    needs:
    - render-site

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
